apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homelab-testapp
  namespace: argocd
  labels:
    app.kubernetes.io/managed-by: argocd
    homelab.dev/managed-by: argocd
    homelab.dev/layer: apps
    app.kubernetes.io/name: homelab-testapp
    app.kubernetes.io/part-of: applications
  annotations:
    argocd.argoproj.io/sync-wave: "30"
    homelab.dev/description: "Test application for CI/CD pipeline validation"
spec:
  project: default
  source:
    repoURL: git@github.com:erauner/homelab-testapp.git
    targetRevision: main
    path: chart
    helm:
      releaseName: homelab-testapp
      valuesObject:
        smokeTestMarker: "BATCH-20260123-151827"
        # Boot delay for testing sync verification (30s per component)
        globalBootDelaySeconds: 60

  destination:
    server: https://kubernetes.default.svc
    namespace: tenant-123-prod

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true

  revisionHistoryLimit: 10
