apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: security-priority-classes
  namespace: argocd
  labels:
    homelab.dev/layer: security
    homelab.dev/category: priority-classes
  annotations:
    # Run early - priority classes need to exist before pods using them
    # Before namespaces (-89) since priority classes are cluster-scoped
    argocd.argoproj.io/sync-wave: "-90"
spec:
  project: infrastructure
  source:
    repoURL: git@github.com:erauner/homelab-k8s.git
    targetRevision: master
    path: ./security/priority-classes/overlays/erauner-home
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
    - ServerSideApply=false
    - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
