apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-80"
spec:
  project: default
  source:
    repoURL: https://github.com/erauner12/homelab-k8s-starter.git
    targetRevision: master
    path: operators/cert-manager/overlays/erauner-cloud
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=false
