apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-79"
spec:
  project: default
  source:
    repoURL: https://github.com/erauner12/homelab-k8s-starter.git
    targetRevision: main
    path: operators/external-secrets/overlays/erauner-cloud
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
      - Replace=true
