apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  # Enables "LOGIN VIA SSO" and points ArgoCD at the Dex issuer in homelab.
  # Dex itself is managed separately under infrastructure/dex.
  url: https://argocd.erauner.dev
  oidc.config: |
    name: Dex
    issuer: https://dex.erauner.dev
    clientId: argocd
    clientSecret: $argocd-oidc-secret:oidc.dex.clientSecret
    requestedScopes: ["openid", "profile", "email", "groups", "offline_access"]
    requestedIDTokenClaims: {"groups": {"essential": true}}
    claimMapping:
      groups: "https://claims.erauner.dev/groups"
