apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-oidc-secret
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-secrets-manager
  target:
    name: argocd-oidc-secret
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
      data:
        oidc.dex.clientSecret: "{{ .dex_argocd_secret }}"
  dataFrom:
    - extract:
        key: k8s-dex
        property: dex_argocd_secret
