version: '3'

tasks:
  preflight:
    desc: Run local preflight checks
    cmds:
      - ./scripts/pre-bootstrap-test.sh

  bootstrap:plan:
    desc: Show bootstrap plan
    cmds:
      - ./bin/homelabctl bootstrap plan

  bootstrap:run:
    desc: Run bootstrap
    cmds:
      - ./bin/homelabctl bootstrap run --kubeconfig ~/.kube/config
