version: '3'

tasks:
  preflight:
    desc: Run local preflight checks
    cmds:
      - ./scripts/pre-bootstrap-test.sh

  static:validate:
    desc: Render and schema-validate key targets (auto full/fast)
    cmds:
      - ./scripts/static-validate.sh

  static:validate:fast:
    desc: Render and schema-validate non-helm targets
    cmds:
      - ./scripts/static-validate-fast.sh

  static:validate:full:
    desc: Render and schema-validate all targets (requires Helm 3)
    cmds:
      - ./scripts/static-validate-full.sh

  bootstrap:plan:
    desc: Show bootstrap plan
    cmds:
      - ./bin/homelabctl bootstrap plan

  bootstrap:run:
    desc: Run bootstrap
    cmds:
      - ./bin/homelabctl bootstrap run --kubeconfig ~/.kube/config

  talos:local:up:
    desc: Create local Talos cluster and bootstrap ArgoCD local profile
    cmds:
      - ./scripts/talos/local-up.sh

  talos:local:status:
    desc: Show local Talos status/context
    cmds:
      - ./scripts/talos/local-status.sh

  talos:local:validate:
    desc: Run shared smoke checks on local Talos profile
    cmds:
      - ./scripts/talos/local-validate.sh

  smoke:local:
    desc: Run smoke checks on local profile
    cmds:
      - ./smoke/scripts/run.sh --profile local --context ${CLUSTER_NAME:-starter-talos}

  smoke:cloud:
    desc: Run smoke checks on cloud profile
    cmds:
      - ./smoke/scripts/run.sh --profile cloud

  talos:local:down:
    desc: Destroy local Talos cluster
    cmds:
      - ./scripts/talos/local-down.sh

  argocd:get-admin:
    desc: Print ArgoCD admin credentials for the active cluster context
    cmds:
      - ./scripts/argocd-get-admin.sh

  argocd:ui:
    desc: Port-forward ArgoCD UI and print login credentials
    cmds:
      - ./scripts/argocd-ui.sh

  cloud:e2e:
    desc: Provision cloud cluster, bootstrap ArgoCD, and validate app health (keeps cluster running)
    cmds:
      - ./scripts/cloud-e2e-bootstrap.sh

  cloud:e2e:destroy:
    desc: Run cloud e2e and destroy cluster on exit
    cmds:
      - ./scripts/cloud-e2e-bootstrap.sh --destroy-on-exit
