version: '3'

tasks:
  preflight:
    desc: Run local preflight checks
    cmds:
      - ./scripts/pre-bootstrap-test.sh

  bootstrap:plan:
    desc: Show bootstrap plan
    cmds:
      - ./bin/homelabctl bootstrap plan

  bootstrap:run:
    desc: Run bootstrap
    cmds:
      - ./bin/homelabctl bootstrap run --kubeconfig ~/.kube/config

  kind:up:
    desc: Create local kind cluster and deploy starter profile
    cmds:
      - ./scripts/kind-up.sh

  kind:status:
    desc: Show status of local kind deployment
    cmds:
      - ./scripts/kind-status.sh

  kind:validate:
    desc: Validate ArgoCD sync and workload readiness on local kind profile
    cmds:
      - ./scripts/kind-validate.sh

  kind:down:
    desc: Delete local kind cluster
    cmds:
      - ./scripts/kind-down.sh
