version: '3'

tasks:
  preflight:
    desc: Run local preflight checks
    cmds:
      - ./scripts/pre-bootstrap-test.sh

  static:validate:
    desc: Render and schema-validate key targets (auto full/fast)
    cmds:
      - ./scripts/static-validate.sh

  static:validate:fast:
    desc: Render and schema-validate non-helm targets
    cmds:
      - ./scripts/static-validate-fast.sh

  static:validate:full:
    desc: Render and schema-validate all targets (requires Helm 3)
    cmds:
      - ./scripts/static-validate-full.sh

  bootstrap:plan:
    desc: Show bootstrap plan
    cmds:
      - ./bin/homelabctl bootstrap plan

  bootstrap:run:
    desc: Run bootstrap
    cmds:
      - ./bin/homelabctl bootstrap run --kubeconfig ~/.kube/config

  kind:up:
    desc: Create local kind cluster and deploy starter profile
    cmds:
      - ./scripts/kind-up.sh

  kind:status:
    desc: Show status of local kind deployment
    cmds:
      - ./scripts/kind-status.sh

  kind:validate:
    desc: Validate ArgoCD sync and workload readiness on local kind profile
    cmds:
      - ./scripts/kind-validate.sh

  kind:down:
    desc: Delete local kind cluster
    cmds:
      - ./scripts/kind-down.sh

  talos:local:up:
    desc: Create local Talos cluster and bootstrap ArgoCD + kind profile
    cmds:
      - ./scripts/talos/local-up.sh

  talos:local:status:
    desc: Show local Talos status/context
    cmds:
      - ./scripts/talos/local-status.sh

  talos:local:down:
    desc: Destroy local Talos cluster
    cmds:
      - ./scripts/talos/local-down.sh

  cloud:e2e:
    desc: Provision cloud cluster, bootstrap ArgoCD, and validate app health (keeps cluster running)
    cmds:
      - ./scripts/cloud-e2e-bootstrap.sh

  cloud:e2e:destroy:
    desc: Run cloud e2e and destroy cluster on exit
    cmds:
      - ./scripts/cloud-e2e-bootstrap.sh --destroy-on-exit
