apiVersion: v1
kind: Namespace
metadata:
  name: auth
  labels:
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
    homelab.dev/layer: security
    homelab.dev/managed-by: argocd
