# Backup system namespace - shared backup infrastructure
# Created for B2 backup credentials (issue #1183, #1184, #1185)
apiVersion: v1
kind: Namespace
metadata:
  name: backup-system
  labels:
    homelab.dev/layer: infra
    homelab.dev/managed-by: argocd
    homelab.dev/type: backup
    pod-security.kubernetes.io/enforce: baseline
  annotations:
    homelab.dev/description: "Shared backup system infrastructure"
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/warn: baseline
