apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-tailscale-access
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-40"
spec:
  project: infrastructure
  source:
    repoURL: https://github.com/erauner12/homelab-k8s-starter.git
    targetRevision: main
    path: infrastructure/argocd-tailscale-access/base
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
      - Replace=true
