apiVersion: v1
kind: Secret
metadata:
  name: sops-age
  namespace: argocd
type: Opaque
stringData:
  age.agekey: |
    # created: 2025-05-15T17:43:28-05:00
    # public key: age1jjls7fqmd742cxu5pvuecvfg9hwxchpt2xxf5uuh72ypus9fzazqkzwk3y
    AGE-SECRET-KEY-1TQGDGAGATA58RW72AMGWAX8LHW42DN90VAW5Q0T7R3UT4DTNRM4SYPKDMA
