# Homarr namespace - dashboard
# Migrated from CreateNamespace=true (issue #950)
apiVersion: v1
kind: Namespace
metadata:
  name: homarr
  labels:
    homelab.dev/layer: apps
    homelab.dev/managed-by: argocd
    homelab.dev/type: dashboard
    homelab.dev/storage-backend: truenas
    pod-security.kubernetes.io/enforce: restricted
  annotations:
    homelab.dev/description: "Homarr dashboard"
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/warn: restricted
