# Knowledge namespace - bookmark and knowledge management apps
# Migrated from CreateNamespace=true (issue #950)
# Uses baseline PodSecurity - karakeep requires s6-overlay which starts as root
apiVersion: v1
kind: Namespace
metadata:
  name: knowledge
  labels:
    homelab.dev/layer: apps
    homelab.dev/managed-by: argocd
    homelab.dev/type: knowledge
    # Storage intent: Longhorn for bookmark/knowledge management
    homelab.dev/storage-backend: longhorn
    pod-security.kubernetes.io/enforce: baseline
  annotations:
    homelab.dev/description: "Knowledge and bookmark management apps"
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/warn: baseline
