# Plane-staging namespace - staging environment for Plane
# Migrated from infrastructure/namespaces (issue #950)
apiVersion: v1
kind: Namespace
metadata:
  name: plane-staging
  labels:
    homelab.dev/layer: apps
    homelab.dev/managed-by: argocd
    homelab.dev/type: staging
    homelab.dev/environment: staging
    pod-security.kubernetes.io/enforce: restricted
  annotations:
    homelab.dev/description: "Plane staging environment"
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/warn: restricted
