apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: longhorn-prometheus
  namespace: longhorn-system
  labels:
    app: longhorn-manager
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: longhorn-manager
  namespaceSelector:
    matchNames:
      - longhorn-system
  endpoints:
    - port: manager
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
      relabelings:
        # Add kubernetes_node label from nodename
        - sourceLabels: [__meta_kubernetes_pod_node_name]
          targetLabel: kubernetes_node
