apiVersion: longhorn.io/v1beta2
kind: Setting
metadata:
  name: storage-over-provisioning-percentage
  namespace: longhorn-system
# Controls cluster-level scheduling: how much total PVC capacity can be
# scheduled relative to physical disk space. Does NOT prevent individual
# volumes from exceeding their PVC limits (use alerts for that - see #1155).
#
# Example: With 100GB physical storage and 110% setting, Longhorn allows
# scheduling up to 110GB total PVC capacity before blocking new volumes.
#
# HOMELAB MODE: Tightened from 125% to 110% for aggressive disk protection.
# Combined with storage-minimal-available-percentage (15%), this provides
# a two-tier defense against disk exhaustion.
value: "110"
