apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared-apps
spec:
  template:
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: cloudflared-apps
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
