apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeeringPolicy
metadata:
  name: home-bgp-policy
spec:
  nodeSelector:
    matchLabels:
      bgp: "enable"
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: DoesNotExist
  # ——— All nodes labelled bgp=enable can peer BGP; control-plane nodes are excluded by selector. ———
  # ControlPlane-only pinning was removed on 2025-06-23 (commit 9baeab2) in favor of this stricter guard.
  # This enables the multi-speaker mesh as documented in docs/networking/BGP.md.
  virtualRouters:
    - localASN: 65000
      exportPodCIDR: true
      serviceSelector: {}              # advertise every LB Service
      serviceAdvertisements:
        - LoadBalancerIP
      neighbors:
        - peerAddress: '192.168.1.1/32'
          peerASN: 64512
          eBGPMultihopTTL: 2
      # An empty service selector selects all services of type LoadBalancer.
      # serviceSelector: {}
