apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: home-pool-15
  labels:
    homelab.dev/layer: config
    homelab.dev/component: cilium-lb
spec:
  serviceSelector:
    matchLabels:
      lb-pool: "15"
  blocks:
    - start: 10.15.0.1
      stop: 10.15.0.253
