apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: external-secrets-operator
  namespace: external-secrets
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: external-secrets
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 8080  # Metrics
    - from:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 9443  # Webhook
  egress:
    # Kubernetes API server - use CIDR since it's a service IP, not a pod
    - to:
        - ipBlock:
            cidr: 10.96.0.1/32
      ports:
        - protocol: TCP
          port: 443
    # Also allow to kube-system pods (API server endpoints)
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: TCP
          port: 6443  # API server port on nodes
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: security
      ports:
        - protocol: TCP
          port: 8080  # 1Password Connect
    - ports:
        - protocol: UDP
          port: 53  # DNS
