apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  labels:
    homelab.dev/layer: infra
    homelab.dev/category: platform
  annotations:
    argocd.argoproj.io/sync-wave: "-80"
spec:
  project: infrastructure
  source:
    repoURL: git@github.com:erauner/homelab-k8s.git
    targetRevision: master
    path: ./operators/external-secrets/overlays/erauner-home
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
    - ServerSideApply=true
    - Replace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
