apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale-operator
  namespace: argocd
  labels:
    homelab.dev/layer: infra
    homelab.dev/category: platform
  annotations:
    # Deploy after core operators (cert-manager, external-secrets, kyverno)
    # but before application-level operators
    argocd.argoproj.io/sync-wave: "-48"
spec:
  project: infrastructure
  source:
    repoURL: git@github.com:erauner/homelab-k8s.git
    targetRevision: master
    path: ./operators/tailscale-operator/overlays/erauner-home
  destination:
    server: https://kubernetes.default.svc
    namespace: tailscale
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=false
      - Replace=true  # Required for CRDs
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
