apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
spec:
  template:
    spec:
      containers:
        - name: operator
          env:
            - name: OPERATOR_INITIAL_TAGS
              value: ""
            - name: PROXY_TAGS
              value: ""
