# KSOPS secret generator for Tailscale OAuth credentials
# This reads the SOPS-encrypted secret and creates the operator-oauth
# secret that the Tailscale operator uses for authentication
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: operator-oauth-secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - operator-oauth-secret.sops.yaml
