apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-apps-token
    namespace: network
type: Opaque
stringData:
    cf-tunnel-token: ENC[AES256_GCM,data:bX0qemzWG0dvEPVfnOp4Pd5F/+eVkZjy0wdEYiW9BgAP0rsNjvWzRdhQe24KsTe9zyIDBDDaWU8/KMk7mpnd5YNQj7Q+yC+uHMWM5yWZS3yNOSl+MIKXeKautL2MuQ8rYUn0aWDZrCOucJQaGrkVMtAa+G7bYIjYDt3gcF1TN1G/eVFGwpPx/7neh7iQdSUFJEFVZmwaHcivkvBemxtTVG0pdKZH56CpcciVaDTQQBQzbhaP,iv:j7/g0TJ4i/lkdBME7EIQuRitSbp404alCDiPd3cB+Oo=,tag:czrPxyyOtAp7Hh0eK9Wl8w==,type:str]
sops:
    age:
        - recipient: age1jjls7fqmd742cxu5pvuecvfg9hwxchpt2xxf5uuh72ypus9fzazqkzwk3y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZdEtsbTM4NitJckhCdGRY
            YjZkU1RDa1ptRzE0WTJpZVRZVG4rd1JreWxFCnFoT3dOTHZ2Q2dHTCtwalpLWkRw
            ZU55N0J5UEUxQkNmeTI3U2xYcmdPdmMKLS0tIHZKRTk3Sm5oR1lGQ3pTdUNGQnAv
            MnJoR2ZZZ2xXeUpjRzc1RHlwWDluYzQKg6ODI9KG7Qa2IYiQojyd49tc/1vA50hw
            zjwN4RGQe5nvTPjZQsEluAge6g74IaEQGDXfoNfgyf7Jd0ziDPkjAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T11:19:26Z"
    mac: ENC[AES256_GCM,data:VHPjmEvXmRNxdKVkMNigT6U2ITbPETJIDgpT6r3aaQVfEb3RfHJSqlPOqEiiL5vRS2gNdV9C/1gt/1DM2kMHVfzCTSC4Wk3+WsukdM1MYLQbR8+6wLUP/M9rBGIAuchpVPkMvZtcskZTYaKBMLlE+QKqH1MZeS71SLVLXudSJFg=,iv:ZsjL3WNZ8YxUxqRZBUXmrKtxTB6w9OHCB4A4MAnhKWA=,tag:N1xvBFvhHr0gmls/+17PIg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
