apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: argocd
  namespace: argocd
spec:
  values:
    configs:
      cm:
        oidc.config: |
          name: Dex
          issuer: https://dex.erauner.dev
          clientId: argocd
          clientSecret: $argocd-oidc-secret:oidc.dex.clientSecret
          requestedScopes: ["openid", "profile", "email", "groups", "offline_access"]
          requestedIDTokenClaims: {"groups": {"essential": true}}
          claimMapping:
            groups: "https://claims.erauner.dev/groups"

      rbac:
        policy.default: role:readonly
        scopes: '[groups]'
        policy.csv: |
          # Default policies
          p, role:admin, applications, *, */*, allow
          p, role:admin, clusters, *, *, allow
          p, role:admin, repositories, *, *, allow
          p, role:admin, certificates, *, *, allow
          p, role:admin, projects, *, *, allow
          p, role:admin, accounts, *, *, allow
          p, role:admin, gpgkeys, *, *, allow
          p, role:readonly, applications, get, */*, allow
          p, role:readonly, clusters, get, *, allow
          p, role:readonly, repositories, get, *, allow
          p, role:readonly, certificates, get, *, allow
          p, role:readonly, projects, get, *, allow

          # Group mappings from Auth0 claims
          g, app:argocd:admins, role:admin
          g, app:argocd:users, role:readonly
