apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: longhorn-tls
  namespace: longhorn-system
spec:
  secretName: longhorn-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-cloudflare-home
  dnsNames:
    - longhorn.erauner.dev
