apiVersion: longhorn.io/v1beta2
kind: Setting
metadata:
  name: orphan-resource-auto-deletion
  namespace: longhorn-system
value: "replica-data"  # Auto-delete orphaned replica data after grace period (300s)
