apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: security-app-of-apps
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-110"
spec:
  project: default
  source:
    repoURL: https://github.com/erauner12/homelab-k8s-starter.git
    targetRevision: main
    path: clusters/local/argocd/security
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
