apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
  namespace: argocd
spec:
  template:
    spec:
      initContainers:
        - name: install-ksops
          image: public.ecr.aws/docker/library/alpine:3.23
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -e
              apk add --no-cache ca-certificates curl tar
              KSOPS_VERSION="4.3.2"
              curl -fsSL "https://github.com/viaduct-ai/kustomize-sops/releases/download/v${KSOPS_VERSION}/ksops_${KSOPS_VERSION}_Linux_x86_64.tar.gz" | tar xz -C /custom-tools/ ksops
              SOPS_VERSION="3.8.1"
              curl -fsSL -o /custom-tools/sops "https://github.com/getsops/sops/releases/download/v${SOPS_VERSION}/sops-v${SOPS_VERSION}.linux.amd64"
              chmod +x /custom-tools/*
              mkdir -p /custom-tools/kustomize-plugin/viaduct.ai/v1/ksops/
              cp /custom-tools/ksops /custom-tools/kustomize-plugin/viaduct.ai/v1/ksops/ksops
          volumeMounts:
            - name: custom-tools
              mountPath: /custom-tools
      containers:
        - name: argocd-repo-server
          volumeMounts:
            - name: custom-tools
              mountPath: /usr/local/bin/ksops
              subPath: ksops
            - name: custom-tools
              mountPath: /usr/local/bin/sops
              subPath: sops
            - name: sops-age
              mountPath: /home/argocd/.config/sops/age
              readOnly: true
            - name: custom-tools
              mountPath: /home/argocd/.config/kustomize/plugin
              subPath: kustomize-plugin
          env:
            - name: SOPS_AGE_KEY_FILE
              value: /home/argocd/.config/sops/age/age.agekey
            - name: XDG_CONFIG_HOME
              value: /home/argocd/.config
            - name: KUSTOMIZE_PLUGIN_HOME
              value: /home/argocd/.config/kustomize/plugin
      volumes:
        - name: custom-tools
          emptyDir: {}
        - name: sops-age
          secret:
            secretName: sops-age
