apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.default: role:none  # Deny by default - more secure
  policy.csv: |
    # Admin access
    p, role:admin, applications, *, */*, allow
    p, role:admin, clusters, *, *, allow
    p, role:admin, repositories, *, *, allow
    p, role:admin, certificates, *, *, allow
    p, role:admin, projects, *, *, allow
    p, role:admin, accounts, *, *, allow
    p, role:admin, gpgkeys, *, *, allow
    p, role:admin, exec, create, */*, allow

    # Developer access (read-only + sync)
    p, role:developer, applications, get, */*, allow
    p, role:developer, applications, list, */*, allow
    p, role:developer, applications, sync, */*, allow
    p, role:developer, applications, action/*, */*, allow
    p, role:developer, logs, get, */*, allow
    p, role:developer, exec, create, */*, deny

    # Readonly access
    p, role:readonly, applications, get, */*, allow
    p, role:readonly, applications, list, */*, allow
    p, role:readonly, clusters, get, *, allow
    p, role:readonly, clusters, list, *, allow
    p, role:readonly, repositories, get, *, allow
    p, role:readonly, repositories, list, *, allow
    p, role:readonly, projects, get, *, allow
    p, role:readonly, projects, list, *, allow

    # Explicit user access (TODO: temporary until Auth0 groups are configured)
    g, raunerevan@gmail.com, role:admin

    # Group mappings from Auth0/Dex (when you configure Auth0 to send groups)
    g, platform-admins, role:admin
    g, sre, role:admin
    g, devops, role:developer
    g, developers, role:developer
    g, auditors, role:readonly
  policy.matchMode: glob
  scopes: '[groups, email]'  # Also match on email for user-specific rules
