apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: app-of-apps
  namespace: argocd
spec:
  description: Meta project for root app-of-apps applications
  sourceRepos:
    - https://github.com/erauner12/homelab-k8s-starter.git
    - ssh://git@github.com/erauner12/homelab-k8s-starter.git
    - git@github.com:erauner12/homelab-k8s-starter.git
  destinations:
    - namespace: argocd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
