apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: operators
  namespace: argocd
spec:
  description: Operator installations and cluster-level controllers
  sourceRepos:
    - https://github.com/erauner12/homelab-k8s-starter.git
    - ssh://git@github.com/erauner12/homelab-k8s-starter.git
    - git@github.com:erauner12/homelab-k8s-starter.git
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
