apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflared-apps
  namespace: argocd
  labels:
    homelab.dev/layer: infra
    homelab.dev/category: network
  annotations:
    argocd.argoproj.io/sync-wave: "-70"
spec:
  project: infrastructure
  source:
    repoURL: git@github.com:erauner/homelab-k8s.git
    targetRevision: master
    path: ./infrastructure/cloudflared-apps/overlays/erauner-cloud
  destination:
    server: https://kubernetes.default.svc
    namespace: network
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
