apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-definitions
  namespace: argocd
  labels:
    homelab.dev/layer: infra
    homelab.dev/category: platform
  annotations:
    argocd.argoproj.io/sync-wave: "-76"
spec:
  project: infrastructure
  source:
    repoURL: git@github.com:erauner/homelab-k8s.git
    targetRevision: master
    path: ./infrastructure/external-secrets-definitions/overlays/erauner-cloud
    # kustomize.buildOptions is set globally in argocd-cm configmap
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
