apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: network-secrets
  namespace: argocd
  labels:
    homelab.dev/layer: infra
    homelab.dev/category: secrets
  annotations:
    # Needs argocd-runtime (ksops) and external-secrets-definitions (SOPS/KSOPS setup) first.
    argocd.argoproj.io/sync-wave: "-75"
spec:
  project: infrastructure
  source:
    repoURL: git@github.com:erauner/homelab-k8s.git
    targetRevision: master
    path: ./infrastructure/network-secrets/overlays/erauner-cloud
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
