apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: observability
  namespace: argocd
  labels:
    homelab.dev/managed-by: "argocd"
    homelab.dev/layer: "infrastructure"
    homelab.dev/cluster: "cloud"
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
    homelab.dev/description: "Cloud observability project"
spec:
  description: Minimal observability stack for cloud cluster
  sourceRepos:
    - 'ssh://git@github.com/erauner/homelab-k8s'
    - 'git@github.com:erauner/homelab-k8s.git'
    - 'https://prometheus-community.github.io/helm-charts'
  destinations:
    - namespace: observability
      server: https://kubernetes.default.svc
    - namespace: kube-system
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
    # kube-prometheus-stack ships CRDs under crds/; ArgoCD must be allowed to
    # apply CustomResourceDefinitions before it can create Prometheus/ServiceMonitor/etc.
    - group: 'apiextensions.k8s.io'
      kind: CustomResourceDefinition
    - group: 'rbac.authorization.k8s.io'
      kind: ClusterRole
    - group: 'rbac.authorization.k8s.io'
      kind: ClusterRoleBinding
    - group: 'admissionregistration.k8s.io'
      kind: MutatingWebhookConfiguration
    - group: 'admissionregistration.k8s.io'
      kind: ValidatingWebhookConfiguration
    - group: 'monitoring.coreos.com'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
